name: work distribution
on: workflow_call
jobs:
  work_1:
    runs-on: [self-hosted, Linux, X64]
    steps:
    - name: job1
      run: echo work 1 is executed

#   job-2:
#     runs-on: ubuntu-latest
#     if: ${{needs.job-1.steps.outputs == true}} 
#     steps:
#     - run: echo job 2 is executed
  
#   job-3:
#     runs-on: ubuntu-latest
#     if: ${{needs.job-1.steps.outputs == false}} 
#     steps:
#     - run: echo job 2 not executed
    
#   job-2:
#     if: ${{ success() }} 
#     runs-on: [self-hosted, Linux, X64, my-runner]
#     steps:
#     - run: echo job 2 is executed

  work_2:
    runs-on: [self-hosted, Linux, X64, my-runner]
    needs: [work_1]
    if: needs.work_1.result == 'success'
    steps:
    - run: echo work_2 executed after success of work_1 on a different runner
  
#   job-3:
#     runs-on: ubuntu-latest
#     if: ${{ failure() }} 
#     runs-on: [self-hosted, Linux, X64]
#     steps:
#     - run: echo job 2 not executed
