name: adding jobs in workflow

on: workflow_call
jobs:
  reusing_first_job:
    runs-on: ubuntu-latest
    steps:
      - name: reused 1st action
        uses: actions/setup-node@v3  
  reusing_second_job:
    runs-on: ubuntu-latest
    steps:
      - name: reused 2nd action
        uses: docker://alpine:3.8
