name: GitHub Actions
on: workflow_call
jobs:
  run-job:
    runs-on: ubuntu-latest
    steps:
      - run: npm install -g bats
      - uses: actions/checkout@v3
      - name: this is a multi-line script
        run: |
          echo line 1
          echo line 2
          echo line 3
      
  uses-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
